// Layout
export { Nav } from './Nav'
export { Onboarding } from './Onboarding'
export { FormularioOnboarding } from './FormularioOnboarding'
export { Footer } from './Footer'
export { Reveal } from './Reveal'
export { UrgencyBar } from './UrgencyBar'
export { WhatsAppButton } from './WhatsAppButton'
export { ScrollProgress } from './ScrollProgress'
export { AnimatedNumber } from './AnimatedNumber'
export { TrustBadges } from './TrustBadges'
export { BorderBeamButton } from './BorderBeamButton'
export { PWAInstaller } from './PWAInstaller'

// Sections
export { HeroSection } from './sections/HeroSection'
export { AboutSection } from './sections/AboutSection'
export { AppPreviewSection } from './sections/AppPreviewSection'
export { EspejoSection } from './sections/EspejoSection'
export { ExamenesSection } from './sections/ExamenesSection'
export { PagoSection } from './sections/PagoSection'
export { ProblemaSection } from './sections/ProblemaSection'
export { ProgramaSection } from './sections/ProgramaSection'
export { ResultadosSection } from './sections/ResultadosSection'
export { PlanesSection } from './sections/PlanesSection'
export { CTASection } from './sections/CTASection'

// Context
export { ProfileProvider, useProfile } from './ProfileContext'
export { UserProvider, useUser } from './UserContext'
